name: GitHub Actions Demo
on: [push]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: prepare jobs
        run: sudo apt-get install -y autopoint gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64
      - name: clone aria2
        run: sudo git clone --depth 1 --branch release-1.36.0 https://github.com/aria2/aria2.git && cd aria2 && sudo git checkout -b patch && sudo git am -3 ../aria2-*.patch
      - name: mingw-x86_64-w64-build-lib
        run: sudo bash ${{ github.workspace }}/build-scripts/mingw-config/aria2-x86_64-w64-mingw-build-libs
      - name: mingw-x86_64-w64-build-aria2    
        run: cd aria2 && sudo autoreconf -i && sudo bash ${{ github.workspace }}/build-scripts/mingw-config/aria2-x86_64-w64-mingw-config 
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."